<a href="https://colab.research.google.com/github/Fernarthit/data_viz_2022/blob/main/Data_Structure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Data Structure (โครงสร้างข้อมูล)
##เก็บข้อมูลไว้ด้วยกันอย่างเป็นระเบียบ

##LIst()
- เป็นอะไรก็ได้
- ลำดับในการเก็บมีความสำคัญ

In [ ]:
List_a  = [1,2,3,4,5,6] # [] sq brackets

In [ ]:
List_a

[1, 2, 3, 4, 5, 6]

In [ ]:
List_b = ['ab' ,2,3.15,List_a]

In [ ]:
List_b

['ab', 2, 3.15, [1, 2, 3, 4, 5, 6]]

##indexing การชี้สมาชิกใน list ด้วยเลขลำดับของ list

In [ ]:
List_a[3]

4

In [ ]:
List_b[3]

[1, 2, 3, 4, 5, 6]

In [ ]:
List_b[3][2]

3

In [ ]:
List_a[6] #ชี้ลำดับเกินใน list

IndexError: ignored

In [ ]:
List_a[-1] #Index -1 หมายถึงมีสมาชิกเยอะมาก -1คือตัวสุดท้ายของ list

6

In [ ]:
List_a[-4] #เป็นลำดับที่ 4 นับจากข้างหลัง

3

##การสร้าง LIst()

In [ ]:
List_x1 = [] #แบบที่ 1 สร้างสัญลักษณ์ list ขึ้นมา
List_x2 = list() #แบบที่ 2

In [ ]:
print(List_x1)
print(List_x2)

[]
[]


##เพิ่มสมาชิกเข้าไปใน list ด้วย append()

In [ ]:
List_x1.append(2)

In [ ]:
List_x1

[2]

In [ ]:
List_x1.append(4)
print(List_x1)

[2, 4]


In [ ]:
List_x1[0]

2

In [ ]:
List_x1[-1]

4

In [ ]:
List_x2

[]

In [ ]:
List_x2.append( 'ha' )

In [ ]:
List_x2

['ha', 'ha', 'ha', 'ha', 'ha']

In [ ]:
List_x1.append('ha')

In [ ]:
List_x1

['ha']

In [ ]:
List_x1.pop( ) #pop หมายถึง ลบตัวสุดท้ายออก

'ha'

In [ ]:
List_x1

[]

In [ ]:
List_x1.pop()
print(List_x1)

IndexError: ignored

##len() ตรวจสอบจำนวนสมาชิกของ list

In [ ]:
print(List_b)
print(len(List_b))

['ab', 2, 3.15, [1, 2, 3, 4, 5, 6]]
4


In [ ]:
len(List_a) #จำนวนสมาชิกของ list a

6

#String is a list of characters

In [ ]:
st_stat = 'Department of Statistics,  Faculty of Science'

In [ ]:
st_stat[11]  #ตัวอักษรที่ 11 คือ

'o'

In [ ]:
len(st_stat) #จำนวนตัวอักษรทั้งหมด

45

#List Slicing : 

- List[จุดเริ่มต้น : จุดสุดท้าย]
- List[จุดเริ่มต้น : จุดสุดท้าย : stop]
- หน้า : ไม่ต้องใส่อะไรก็ได้ จะเริ่มนับตั้งแต่ 0 จนถึงตัวที่กำหนด

In [ ]:
List_a

[1, 2, 3, 4, 5, 6]

In [ ]:
List_a[3]

4

## : colon

In [ ]:
List_a[-6:-2] # จะไม่นับตัวสุดท้าย เช่น -6 : -2 ก็จะไม่มีลำดับที่ -2

[1, 2, 3, 4]

In [ ]:
List_a[:3] #- หน้า : ไม่ต้องใส่อะไรก็ได้ จะเริ่มนับตั้งแต่ 0 จนถึงตัวที่กำหนด

[1, 2, 3]

In [ ]:
List_a[:] #จะนับให้ทั้งหมด

[1, 2, 3, 4, 5, 6]

##step

In [ ]:
List_c = [1,2,3,4,5,6,7,8,9,10,11,12,13]

In [ ]:
List_c[:11] #10ตัวแรก

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [ ]:
List_c[:10:]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
List_c[:10:2] #ห่างกัน2ตัว

[1, 3, 5, 7, 9]

In [ ]:
List_c[::2] #iรันทุกตัว และห่างกัน 2 ตัว

[1, 3, 5, 7, 9, 11, 13]

##range( )

In [ ]:
a = list(range(21))

In [ ]:
a #list ของตัวเลขจำนวน 21 ตัว

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [ ]:
list(range(1,21)) #จุดเริ่มต้นคือ 1 จุดสุดท้ายตำแหน่งที่ 21

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

#HW2
####คำนวณเวลาเป็นวินาทีของเวลาต่อไปนี้โดยใช้คำสั่ง split() ช่วย (print ออกมาให้สวยงาม)

- 12:30:15
- 13:41:07
- 09:11:50
- 21:30:15
- 03:10:15

In [ ]:
#01:00:00

a = 1*60*60
print(a)

3600


In [ ]:
#12:30:15

a = (12*60*60) + (30*60) + 15
print(f'12:30:15 แปลงเป็นวินาทีได้ {a} วินาที')

12:30:15 แปลงเป็นวินาทีได้ 45015 วินาที


In [ ]:
#13:41:07

b = (13*60*60) + (41*60) + 7
print(f'13:41:07 แปลงเป็นวินาทีได้ {b} วินาที')

13:41:07 แปลงเป็นวินาทีได้ 49267 วินาที


In [ ]:
#09:11:50

c = (9*60*60) + (11*60) + 50
print(f'09:11:50 แปลงเป็นวินาทีได้ {c} วินาที')

09:11:50 แปลงเป็นวินาทีได้ 33110 วินาที


In [ ]:
#21:30:15

d = (21*60*60) + (30*60) + 15
print(f'21:30:15 แปลงเป็นวินาทีได้ {d} วินาที')

21:30:15 แปลงเป็นวินาทีได้ 77415 วินาที


In [ ]:
#03:10:15

e = (3*60*60) + (10*60) + 15
print(f'03:30:15 แปลงเป็นวินาทีได้ {e} วินาที')

03:30:15 แปลงเป็นวินาทีได้ 11415 วินาที


#Dictionary
- คล้าย list
- index เป็นอะไรก็ได้ ไม่จำเป็นต้องเป็นตัวเลขลำดับ
- ลำดับไม่มีความสำคัญ

##สร้าง Dictionary

In [ ]:
dict_a = {1: 'Happy' , 'N' : 'New' , '2022' :  'Year' } # {  } curly brackets

###การชี้สมาชิกใน Dictionary

In [ ]:
dict_a[1]

'Happy'

In [ ]:
dict_a['N']

'New'

In [ ]:
dict_a.keys()

dict_keys([1, 'N', '2022'])

In [ ]:
dict_a.values()

dict_values(['Happy', 'New', 'Year'])

###การเพิ่มสมาชิกลงไปใน Dictionary

In [ ]:
dict_a[7] = 3.14

In [ ]:
dict_a

{1: 'Happy', '2022': 'Year', 7: 3.14, 'N': 'New'}

In [ ]:
dict_a['N'] = 'NNEEWW' #จะอัพเดตที่ซ้ำเป็นค่าที่กำหนดใหม่

In [ ]:
dict_a #จะอัพเดตที่ซ้ำเป็นค่าที่กำหนดใหม่

{1: 'Happy', '2022': 'Year', 7: 3.14, 'N': 'NNEEWW'}

##Numpy Array
คุณสมบัติ
- เก็บได้แต่ตัวเลข
- อ้างอิงโดยใช้พิกัด ( 2 มิติก็มองเป็น Matrix)

In [10]:
import numpy

###1D array

In [12]:
list_A = [1,2,3,4,5]

In [13]:
arr_a = numpy.array (list_A)

In [14]:
arr_a

array([1, 2, 3, 4, 5])

In [15]:
list_A

[1, 2, 3, 4, 5]

In [16]:
arr_a[0]

1

In [17]:
list_A[0]

1

In [18]:
5 * arr_a #คุณสมบัติ Matrix scalar multilication

array([ 5, 10, 15, 20, 25])

In [19]:
5*list_A

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [20]:
arr_b = numpy.array( [10,20,30,40,50])

In [21]:
print(arr_a)

[1 2 3 4 5]


In [22]:
arr_a + arr_b

array([11, 22, 33, 44, 55])

In [23]:
arr_a.shape

(5,)

###2D array

In [24]:
import numpy as np

In [25]:
arr2_x = np.array([[1,3,5],[7,9,0]])

In [26]:
arr2_x

array([[1, 3, 5],
       [7, 9, 0]])

###np.zeros()

In [27]:
arr2_3_5_0 = np.zeros((3,5))

In [28]:
arr2_3_5_0

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [29]:
arr2_3_5_0[1,2] = 9

In [30]:
arr2_3_5_0 #กำหนดค่า

array([[0., 0., 0., 0., 0.],
       [0., 0., 9., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [31]:
arr2_3_5_0[1,2] #ชี้

9.0

In [32]:
print(list_A) #เปลี่ยนค่าในList()
list_A[-1] = 'Christmas'
print(list_A)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 'Christmas']


### np.ones()

In [33]:
arr2_4= np.ones((5,5))

In [34]:
arr2_4

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [35]:
arr2_5 = 100*np.ones((3,5))

In [36]:
arr2_5

array([[100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.]])

###Matrix operations

การบวก ลบ Matrix $M \pm N$
(ต้องมีขนาดเท่ากัน)

In [ ]:
arr2_4 + arr2_5 # error เพราะมีขนาดไม่เท่ากัน

ValueError: ignored

In [ ]:
arr2_5 + arr2_3_5_0

array([[100., 100., 100., 100., 100.],
       [100., 100., 109., 100., 100.],
       [100., 100., 100., 100., 100.]])

###การคูณ Matrix
- $aM$ scalar * Matrix (scalar คูณกระจายเข้าไปทุกตัวของ Matrix)
- $M\times N$ Matrix * Matrix (แถว*หลัก)

$aM$

In [37]:
5 *   arr_a

array([ 5, 10, 15, 20, 25])

$M\times N$ (dot product)
- (m * n) $\times$ (n,o) = (m,o) (Shape)


In [38]:
mat_a = np.array([[2,3,5],[4,6,7]])
mat_b = np.array([[1,3,5],[2,4,-7]])
mat_c = np.array([[2,3],[4,6],[7,9]])

In [39]:
mat_a

array([[2, 3, 5],
       [4, 6, 7]])

In [40]:
mat_b

array([[ 1,  3,  5],
       [ 2,  4, -7]])

In [41]:
mat_c

array([[2, 3],
       [4, 6],
       [7, 9]])

###axc, bxc

In [42]:
np.dot(mat_a,mat_c)

array([[ 51,  69],
       [ 81, 111]])

In [43]:
np.dot(mat_b,mat_c)

array([[ 49,  66],
       [-29, -33]])

###cxa, cxb

In [44]:
np.dot(mat_c,mat_a)

array([[16, 24, 31],
       [32, 48, 62],
       [50, 75, 98]])

In [45]:
mat_x = np.dot(mat_c,mat_b)
print(mat_x)

[[  8  18 -11]
 [ 16  36 -22]
 [ 25  57 -28]]


In [46]:
mat_a * mat_b # * ไม่ได้คูณตามหลัก matrix เป็นหารคูณตรงตัว

array([[  2,   9,  25],
       [  8,  24, -49]])

### Matrix Slicing

In [47]:
mat_x[:2, :2]

array([[ 8, 18],
       [16, 36]])

#HW 3 

1. สร้าง array ที่มีรูป ต้น Christmas
2. Slice เลข 1 ออกมาจาก array HW3

In [65]:
hw = np.ones((15,14))
hw

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [66]:
hw[1,7] = 8
hw[2,6:9] = 8
hw[3,5:10] = 8
hw[4,4:11] = 8
hw[5,5:10] = 8
hw[6,4:11] = 8
hw[7,3:12] = 8
hw[8,2:13] = 8
hw[9,3:12] = 8
hw[10,2:13] = 8
hw[11,1:14] = 8
hw[12,6:9] = 8
hw[13,6:9] = 8
hw 


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 8., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 8., 8., 8., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 8., 8., 8., 8., 8., 1., 1., 1., 1.],
       [1., 1., 1., 1., 8., 8., 8., 8., 8., 8., 8., 1., 1., 1.],
       [1., 1., 1., 1., 1., 8., 8., 8., 8., 8., 1., 1., 1., 1.],
       [1., 1., 1., 1., 8., 8., 8., 8., 8., 8., 8., 1., 1., 1.],
       [1., 1., 1., 8., 8., 8., 8., 8., 8., 8., 8., 8., 1., 1.],
       [1., 1., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 1.],
       [1., 1., 1., 8., 8., 8., 8., 8., 8., 8., 8., 8., 1., 1.],
       [1., 1., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 1.],
       [1., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [1., 1., 1., 1., 1., 1., 8., 8., 8., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 8., 8., 8., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## Panda Dataframe (แยกออกไปเป็น Notebook เฉพาะ)